So, let's start with the cleaning for every given csv
the possible issues:
* duplicate primary keys
* missing IDs
* invalid emails
* missing emails
* invalid timestamps
* negative and zero product prices
* unknown order statuses
* missing customer references
* missing product references
* missing order references
* invalid negative quantity
* mixed-case status values

In [156]:
import pandas as pd
import re
import os

"* Completely reusable code (I should be able to send the same 4 tables with different data and it should work)"

In [157]:
customers = pd.read_csv(os.path.join("data", "raw", "customers.csv"))
order_items = pd.read_csv(os.path.join("data", "raw", "order_items.csv"))
orders = pd.read_csv(os.path.join("data", "raw", "orders.csv"))
products = pd.read_csv(os.path.join("data", "raw", "products.csv"))

every csv is different, so we need 4 different cleaning functions for this pipeline

In [158]:
customers.head()

   customer_id              email country           created_at
0          1.0  user1@example.com      DE  2024-01-04 23:17:00
1          2.0  user2@example.com      PL  2024-01-29 04:47:00
2          3.0  user3@example.com      DE  2024-03-27 23:57:00
3          4.0  user4@example.com      CZ  2024-01-12 18:27:00
4          5.0  user5@example.com      US  2024-01-04 02:13:00

In [159]:

def clean_customers(customers: pd.DataFrame) -> pd.DataFrame:
    """Drops rows with: invalid/duplicate emails, duplicate\missing id's, invalid date format and lowercases emails"""

    customers["created_at"] = pd.to_datetime(customers["created_at"],
                                             format='%Y-%m-%d %H:%M:%S',
                                             errors="coerce")
    customers["email"] = customers["email"].str.lower()

    customers = customers[
        customers["customer_id"].notna() &
        (customers['customer_id'] >= 0) &
        customers["email"].notna() &
        ~customers["customer_id"].duplicated() &
        ~customers["email"].duplicated() &
        customers["email"].apply(_is_valid_email) &
        customers["created_at"].notna()
    ]
    customers["customer_id"] = customers["customer_id"].astype(int)
    return customers

def _is_valid_email(email):
    """Checks for valid pattern "abc123@abc123.abc" """
    email_pattern = r'^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}$'
    return re.match(email_pattern, str(email)) is not None

In [160]:
customers = clean_customers(customers)
customers[-10:]

     customer_id                email country          created_at
340          341  user341@example.com      ES 2024-02-05 00:36:00
341          342  user342@example.com      US 2024-03-18 23:31:00
342          343  user343@example.com      FR 2024-01-30 19:51:00
343          344  user344@example.com      IT 2024-01-29 20:12:00
344          345  user345@example.com      SE 2024-02-02 21:48:00
345          346  user346@example.com      UA 2024-03-21 03:57:00
346          347  user347@example.com      US 2024-02-09 14:02:00
347          348  user348@example.com      SE 2024-02-16 23:08:00
348          349  user349@example.com      DE 2024-02-07 10:47:00
349          350  user350@example.com      ES 2024-01-23 06:08:00

I will drop all orders which customers id are not in customers

In [161]:
orders.head()

   order_id  customer_id order_status           created_at
0      5001        307.0    completed  2024-05-09 06:49:00
1      5002         71.0    completed  2024-04-16 00:31:00
2      5003        221.0    completed  2024-06-08 22:14:00
3      5004        257.0      pending  2024-07-13 11:04:00
4      5005        204.0    completed  2024-04-03 14:58:00

In [162]:
def clean_orders(orders: pd.DataFrame) -> pd.DataFrame:
    """Drops rows with invalid or non-existant date, customer id or duplicated/invalid order id, and lowercases order status"""
    orders["order_status"] = orders["order_status"].str.lower()
    orders["created_at"] = pd.to_datetime(orders["created_at"],
                                             format='%Y-%m-%d %H:%M:%S',
                                             errors="coerce")
    orders = orders[
        ~orders["order_id"].duplicated() &
        orders["order_id"].notna() &
        (orders["order_id"] >= 0) &
        orders["customer_id"].isin(customers["customer_id"]) &
        orders["created_at"].notna()
        ]
    orders["customer_id"] = orders["customer_id"].astype(int)
    return orders

In [163]:
orders = clean_orders(orders)
orders[-10:]

     order_id  customer_id order_status          created_at
442      5443          215    completed 2024-06-03 12:22:00
443      5444          280    completed 2024-06-01 18:41:00
444      5445          116    completed 2024-07-12 01:18:00
445      5446           11    completed 2024-04-14 02:21:00
446      5447           88    completed 2024-04-10 17:57:00
447      5448           48    cancelled 2024-06-18 15:45:00
448      5449           16    cancelled 2024-04-22 19:56:00
449      5450          223    completed 2024-05-13 06:12:00
452      5452            2    completed 2024-04-03 12:30:00
453      5453            3     returned 2024-04-04 14:00:00

In [164]:
products.head()

   product_id                     name    category    price
0        1001        Toys Product 1001        Toys   810.03
1        1002  Stationery Product 1002  Stationery   797.22
2        1003  Stationery Product 1003  Stationery  1246.05
3        1004  Stationery Product 1004  Stationery  1371.25
4        1005       Books Product 1005       Books  1451.14

In [165]:
def clean_products(products: pd.DataFrame) -> pd.DataFrame:
    """Drops rows with invalid/duplicated product ids, name, without category, or invalid price"""
    products["name"] = products["name"].str.lower()
    products = products[
        ~products["product_id"].isna() &
        (products["product_id"] >= 0) &
        ~products["product_id"].duplicated() &
        ~products["name"].isna() &
        ~products["name"].duplicated() &
        (products["price"] >= 0.01) &
        ~products["category"].isna()
    ]
    return products

In [166]:
products = clean_products(products)
products[-10:]

     product_id                     name    category    price
140        1141      beauty product 1141      Beauty   124.21
141        1142       books product 1142       Books   993.58
142        1143       books product 1143       Books   911.40
143        1144       books product 1144       Books   411.20
144        1145        toys product 1145        Toys   769.49
145        1146  stationery product 1146  Stationery   646.01
146        1147  stationery product 1147  Stationery  1017.97
147        1148      sports product 1148      Sports   730.98
148        1149      beauty product 1149      Beauty   464.01
149        1150   furniture product 1150   Furniture   594.10

In [167]:
order_items.head()

   order_item_id  order_id  product_id  quantity
0              1      5001        1142         5
1              2      5001        1068         3
2              3      5002        1061         1
3              4      5002        1013         4
4              5      5003        1141         4

In [168]:
def clean_order_items(order_items: pd.DataFrame) -> pd.DataFrame:
    order_items = order_items[
        order_items["order_id"].isin(orders["order_id"]) &
        order_items["product_id"].isin(products["product_id"]) &
        (order_items["order_item_id"] >= 0) &
        ~order_items["order_item_id"].duplicated() &
        (order_items["quantity"] >= 1) 
    ]
    return order_items

In [169]:
order_items = clean_order_items(order_items)
order_items[-10:]

     order_item_id  order_id  product_id  quantity
896            897      5446        1106         4
897            898      5446        1078         4
898            899      5447        1071         2
899            900      5447        1049         1
900            901      5447        1034         2
901            902      5448        1069         5
902            903      5449        1060         5
903            904      5449        1060         2
904            905      5449        1007         3
905            906      5450        1123         2

Before moving to the db part, let's combine everything in 1 big table, i think that's the right move here

In [170]:
super_df = order_items.merge(right=orders,
                             how="inner",
                             on="order_id")
super_df.head()

,order_item_id,order_id,product_id,quantity,customer_id,order_status,created_at
0,1,5001,1142,5,307,completed,2024-05-09 06:49:00
1,2,5001,1068,3,307,completed,2024-05-09 06:49:00
2,3,5002,1061,1,71,completed,2024-04-16 00:31:00
3,4,5002,1013,4,71,completed,2024-04-16 00:31:00
4,5,5003,1141,4,221,completed,2024-06-08 22:14:00

In [171]:
super_df = super_df.merge(right=products,
                             how="inner",
                             on="product_id")

super_df["total_cost"] = super_df["quantity"]*super_df["price"]
super_df.head()

,order_item_id,order_id,product_id,quantity,customer_id,order_status,created_at,name,category,price,total_cost
0,1,5001,1142,5,307,completed,2024-05-09 06:49:00,books product 1142,Books,993.58,4967.90
1,2,5001,1068,3,307,completed,2024-05-09 06:49:00,furniture product 1068,Furniture,1113.09,3339.27
2,3,5002,1061,1,71,completed,2024-04-16 00:31:00,furniture product 1061,Furniture,811.24,811.24
3,4,5002,1013,4,71,completed,2024-04-16 00:31:00,toys product 1013,Toys,836.85,3347.40
4,5,5003,1141,4,221,completed,2024-06-08 22:14:00,beauty product 1141,Beauty,124.21,496.84

In [172]:
customers.rename(columns={"created_at": "customer_registration_date"}, inplace=True)

In [173]:
super_df = super_df.merge(right=customers,
                             how="inner",
                             on="customer_id")
super_df.head()

,order_item_id,order_id,product_id,quantity,customer_id,order_status,created_at,name,category,price,total_cost,email,country,customer_registration_date
0,1,5001,1142,5,307,completed,2024-05-09 06:49:00,books product 1142,Books,993.58,4967.90,user307@example.com,IT,2024-01-25 22:15:00
1,2,5001,1068,3,307,completed,2024-05-09 06:49:00,furniture product 1068,Furniture,1113.09,3339.27,user307@example.com,IT,2024-01-25 22:15:00
2,3,5002,1061,1,71,completed,2024-04-16 00:31:00,furniture product 1061,Furniture,811.24,811.24,user71@example.com,US,2024-03-27 20:41:00
3,4,5002,1013,4,71,completed,2024-04-16 00:31:00,toys product 1013,Toys,836.85,3347.40,user71@example.com,US,2024-03-27 20:41:00
4,5,5003,1141,4,221,completed,2024-06-08 22:14:00,beauty product 1141,Beauty,124.21,496.84,user221@example.com,NL,2024-01-28 11:51:00

In [174]:
super_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 906 entries, 0 to 905
Data columns (total 14 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   order_item_id               906 non-null    int64
 1   order_id                    906 non-null    int64
 2   product_id                  906 non-null    int64
 3   quantity                    906 non-null    int64
 4   customer_id                 906 non-null    int32
 5   order_status                906 non-null    str
 6   created_at                  906 non-null    datetime64[us]
 7   name                        906 non-null    str
 8   category                    906 non-null    str
 9   price                       906 non-null    float64
 10  total_cost                  906 non-null    float64
 11  email                       906 non-null    str
 12  country                     906 non-null    str
 13  customer_registration_date  906 non-null    datetime64[us]
dtypes: datetime64[us](2), float64(2), int32(1), int64(4), str(5)
memory usage: 95.7 KB

This is the final table, and now we need to put it in the db

In [175]:
from sqlalchemy import create_engine

In [178]:
engine = create_engine(
    'postgresql+psycopg2://postgres:admin@localhost/db'
)

In [179]:
super_df.to_sql(
    "analytical_table",
    engine,
    if_exists="replace",
    index=False
)

UnicodeDecodeError: 'utf-8' codec can't decode byte 0xd4 in position 61: invalid continuation byte